# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kwcerts < Formula
  desc "Utility to manage self-signed certificates."
  homepage "https://github.com/klearwave"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/klearwave/kwcerts/releases/download/v0.1.0/kwcerts_v0.1.0_Darwin_x86_64.tar.gz"
      sha256 "a12c13250889f5426ed1859008f35908cbb33c48237370b6172adb4f3c3e14b8"

      def install
        bin.install "kwcerts"
      end
    end
    on_arm do
      url "https://github.com/klearwave/kwcerts/releases/download/v0.1.0/kwcerts_v0.1.0_Darwin_arm64.tar.gz"
      sha256 "324204b46d528328c11f75e3f9d94ba54b6abcbdde3d2c6e6d6ab0853df1b790"

      def install
        bin.install "kwcerts"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/klearwave/kwcerts/releases/download/v0.1.0/kwcerts_v0.1.0_Linux_x86_64.tar.gz"
        sha256 "37094060e246b52fff27a074718b9712ffbbcc36c523517e88be359d88302189"

        def install
          bin.install "kwcerts"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/klearwave/kwcerts/releases/download/v0.1.0/kwcerts_v0.1.0_Linux_arm64.tar.gz"
        sha256 "f38b03eb2ea7cd8909db28dc6ffae49be1f548f604e39ad4331419c67ce82d1f"

        def install
          bin.install "kwcerts"
        end
      end
    end
  end

  test do
    system "#{bin}/kwcerts version"
  end
end
