# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kwcerts < Formula
  desc "Utility to manage self-signed certificates."
  homepage "https://github.com/klearwave"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/klearwave/kwcerts/releases/download/v0.3.0/kwcerts_v0.3.0_Darwin_x86_64.tar.gz"
      sha256 "d69812ff9e44d5de4dd9aab0e42dea0f8b83ad44610d2921800c765c0bc7391c"

      def install
        bin.install "kwcerts"
      end
    end
    on_arm do
      url "https://github.com/klearwave/kwcerts/releases/download/v0.3.0/kwcerts_v0.3.0_Darwin_arm64.tar.gz"
      sha256 "51c15b00d54eabf9b7d768b458b825541e422320e0035c9e32110f1c50f47a9c"

      def install
        bin.install "kwcerts"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/klearwave/kwcerts/releases/download/v0.3.0/kwcerts_v0.3.0_Linux_x86_64.tar.gz"
        sha256 "3793042f00802506ce273a7d4248a3a34f38d9d8e45e3677754ffc6656c36984"

        def install
          bin.install "kwcerts"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/klearwave/kwcerts/releases/download/v0.3.0/kwcerts_v0.3.0_Linux_arm64.tar.gz"
        sha256 "1f4fadb15d80a079671310fff35139a1ce11b8fb70886710c1a0cb82ae6ac309"

        def install
          bin.install "kwcerts"
        end
      end
    end
  end

  test do
    system "#{bin}/kwcerts version"
  end
end
