name: "Extract Info"
on: push

jobs:
  json:
    runs-on: macos-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Generate Brew Info"
        run: |
          rm -rf Info
          mkdir -p Info
          cd Formula
          for formula in *.rb; do
            brew info --json "$formula" | jq '.[0]? // .' > ../Info/${formula/%rb/json}
          done

      - name: "Commit Brew Info"
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: 'chore: Generated formula JSON: `brew info --json <formula>`'
          file_pattern: Info
